// ====== CONFIG ======
const OWNER = "byShelby";
const REPO  = "assets";
const BRANCH = "main";

// GitHub Pages base (works for project pages)
const PAGES_BASE = `https://${OWNER.toLowerCase()}.github.io/${REPO}`;

// Manifest generated by Actions
const MANIFEST_URL = `${PAGES_BASE}/data/manifest.json`;

const CATEGORIES = [
  { key: "avatars", titleZh: "Avatars", titleEn: "Avatars", descZh: "头像", descEn: "Avatars" },
  { key: "icons",   titleZh: "Icons",   titleEn: "Icons",   descZh: "图标", descEn: "Icons" },
  { key: "photos",  titleZh: "Photos",  titleEn: "Photos",  descZh: "照片", descEn: "Photos" },
];

const PREVIEW_LIMIT = 6;

// ====== STATE ======
let lang = "zh";
let manifest = null;

const $ = (id) => document.getElementById(id);
const toast = (msg) => {
  const t = $("toast");
  t.textContent = msg;
  t.classList.add("show");
  setTimeout(()=>t.classList.remove("show"), 1200);
};

function setLang(next){
  lang = next;
  $("langBtn").textContent = (lang === "zh" ? "EN" : "中文");
  $("titleText").textContent = (lang === "zh" ? "你的资源库" : "Your Asset Library");
  $("q").placeholder = (lang === "zh"
    ? "搜索：avatar / icon / photo / 文件名"
    : "Search: avatar / icon / photo / filename"
  );
  $("modalSearch").placeholder = (lang === "zh" ? "在当前分类搜索…" : "Search in this category…");
  renderCards();
}

function repoUrl(){
  return `https://github.com/${OWNER}/${REPO}`;
}

function toPagesUrl(path){
  // path like "avatars/avatar-1.jpg"
  return `${PAGES_BASE}/${path}`;
}

function isImage(path){
  return /\.(png|jpg|jpeg|gif|webp|svg)$/i.test(path);
}

function normalizeCategoryPath(p){
  // returns {category, filename}
  const parts = p.split("/").filter(Boolean);
  const cat = parts[0] || "";
  const filename = parts[parts.length - 1] || p;
  return { cat, filename };
}

// ====== UI RENDER ======
function renderCards(){
  if(!manifest) return;

  const q = $("q").value.trim().toLowerCase();
  const cards = $("cards");
  cards.innerHTML = "";

  for(const cat of CATEGORIES){
    const list = (manifest.assets?.[cat.key] || []).filter(isImage);

    const filtered = q
      ? list.filter(p => p.toLowerCase().includes(q))
      : list;

    const count = filtered.length;

    const title = (lang === "zh" ? cat.titleZh : cat.titleEn);
    const desc  = (lang === "zh" ? cat.descZh  : cat.descEn);

    const card = document.createElement("article");
    card.className = "card";

    const top = document.createElement("div");
    top.className = "cardTop";
    top.innerHTML = `
      <div>
        <div class="cardName">${title}</div>
        <div class="cardMeta">${desc}</div>
      </div>
      <div class="badge">${count}</div>
    `;

    const body = document.createElement("div");
    body.className = "cardBody";

    if(count === 0){
      const empty = document.createElement("div");
      empty.className = "empty";
      empty.textContent = (lang === "zh" ? "暂无内容" : "No assets");
      body.appendChild(empty);
    }else{
      const preview = document.createElement("div");
      preview.className = "preview";

      const previewItems = filtered.slice(0, PREVIEW_LIMIT);
      for(const p of previewItems){
        const t = document.createElement("div");
        t.className = "thumb";
        const img = document.createElement("img");
        img.loading = "lazy";
        img.decoding = "async";
        img.src = toPagesUrl(p);
        img.alt = p;
        t.appendChild(img);
        t.addEventListener("click", ()=> openLightbox(p));
        preview.appendChild(t);
      }
      body.appendChild(preview);

      const bottom = document.createElement("div");
      bottom.className = "cardBottom";
      bottom.innerHTML = `
        <div class="mini">${lang === "zh" ? "点击预览，查看更多" : "Click to preview, view all"}</div>
        <button class="btn ghost" type="button">${lang === "zh" ? "View all" : "View all"}</button>
      `;
      bottom.querySelector("button").addEventListener("click", ()=> openGallery(cat.key, filtered));
      body.appendChild(bottom);
    }

    card.appendChild(top);
    card.appendChild(body);
    cards.appendChild(card);
  }
}

// ====== GALLERY ======
let currentGallery = { key: null, list: [] };

function openGallery(key, list){
  currentGallery = { key, list };
  const cat = CATEGORIES.find(c=>c.key===key);
  $("modalCategory").textContent = (lang === "zh" ? cat.titleZh : cat.titleEn);
  $("modalCount").textContent = `(${list.length})`;
  $("modalSearch").value = "";
  renderGallery();
  $("galleryModal").classList.add("show");
  $("galleryModal").setAttribute("aria-hidden", "false");
}

function closeGallery(){
  $("galleryModal").classList.remove("show");
  $("galleryModal").setAttribute("aria-hidden", "true");
}

function renderGallery(){
  const q = $("modalSearch").value.trim().toLowerCase();
  const grid = $("galleryGrid");
  grid.className = "modalBody noScrollbars";
  grid.innerHTML = "";

  const list = q
    ? currentGallery.list.filter(p=>p.toLowerCase().includes(q))
    : currentGallery.list;

  for(const p of list){
    const t = document.createElement("div");
    t.className = "thumb";
    const img = document.createElement("img");
    img.loading = "lazy";
    img.decoding = "async";
    img.src = toPagesUrl(p);
    img.alt = p;
    t.appendChild(img);
    t.addEventListener("click", ()=> openLightbox(p));
    grid.appendChild(t);
  }
}

// ====== LIGHTBOX ======
let currentPath = null;

function openLightbox(path){
  currentPath = path;
  $("lightboxImg").src = toPagesUrl(path);
  $("lightboxName").textContent = path;
  $("openImgBtn").href = toPagesUrl(path);
  $("lightbox").classList.add("show");
  $("lightbox").setAttribute("aria-hidden", "false");
}

function closeLightbox(){
  $("lightbox").classList.remove("show");
  $("lightbox").setAttribute("aria-hidden", "true");
}

async function copyCurrentLink(){
  if(!currentPath) return;
  const url = toPagesUrl(currentPath);
  try{
    await navigator.clipboard.writeText(url);
    toast(lang === "zh" ? "已复制链接" : "Link copied");
  }catch{
    // fallback
    const ta = document.createElement("textarea");
    ta.value = url;
    document.body.appendChild(ta);
    ta.select();
    document.execCommand("copy");
    document.body.removeChild(ta);
    toast(lang === "zh" ? "已复制链接" : "Link copied");
  }
}

// ====== LOAD MANIFEST ======
async function loadManifest(){
  const res = await fetch(MANIFEST_URL, { cache: "no-store" });
  if(!res.ok) throw new Error(`Manifest fetch failed: ${res.status}`);
  manifest = await res.json();
}

// ====== INIT ======
(async function init(){
  $("repoBtn").href = repoUrl();

  $("langBtn").addEventListener("click", ()=>{
    setLang(lang === "zh" ? "en" : "zh");
  });

  $("q").addEventListener("input", renderCards);

  $("closeGallery").addEventListener("click", closeGallery);
  $("galleryModal").addEventListener("click", (e)=>{
    if(e.target === $("galleryModal")) closeGallery();
  });
  $("modalSearch").addEventListener("input", renderGallery);

  $("closeLightbox").addEventListener("click", closeLightbox);
  $("lightbox").addEventListener("click", (e)=>{
    if(e.target === $("lightbox")) closeLightbox();
  });
  $("copyLinkBtn").addEventListener("click", copyCurrentLink);

  // esc to close
  window.addEventListener("keydown", (e)=>{
    if(e.key === "Escape"){
      if($("lightbox").classList.contains("show")) closeLightbox();
      else if($("galleryModal").classList.contains("show")) closeGallery();
    }
  });

  try{
    await loadManifest();
    setLang("zh");
  }catch(err){
    console.error(err);
    $("cards").innerHTML = `<div class="empty">Manifest 加载失败：请确认 data/manifest.json 存在且可访问</div>`;
  }
})();
